# ---------------------------------------------------------------------------
#  Risk Platform: Amazon DynamoDB (Local)
# ---------------------------------------------------------------------------
hyperscaledb.provider=dynamo
hyperscaledb.connection.endpoint=http://localhost:8000
hyperscaledb.connection.region=us-east-1
hyperscaledb.auth.accessKeyId=fakeMyKeyId
hyperscaledb.auth.secretAccessKey=fakeSecretAccessKey
